import {Dimensions, Platform, StyleSheet} from 'react-native';
const {width: screenWidth, height: screenHeight} = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    gap: 40,
    backgroundColor: '#000',
  },
  videoContainer: {
    width: screenWidth,
    height: '100%',
    position: 'relative',
  },
  backgroundVideo: {
    width: screenWidth,
    height: screenHeight - 60,
  },
  heroSecrion: {
    width: screenWidth,
    height: screenHeight - 60,
  },
  contentContainer: {flexDirection: 'column', gap: 40, paddingBottom: 20},
  cardGrid: {
    flexDirection: 'column',
    gap: 20,
  },
  Grid: {
    flexDirection: 'row',
    gap: 12,
    overflow: 'scroll',
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 21,
    fontWeight: 600,
    color: '#fff',
    textTransform: 'capitalize',
  },
  flexbox: {
    flexDirection:'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  paragraph: {
    fontSize: 11,
    fontWeight: 400,
    color: '#ffffff60',
  },
  item: {
    width: screenWidth - 60,
    height: screenWidth - 60,
  },
  imageContainer: {
    flex: 1,
    marginBottom: Platform.select({ios: 0, android: 1}),
    backgroundColor: 'white',
    borderRadius: 8,
  },
  image: {
    ...StyleSheet.absoluteFillObject,
    resizeMode: 'cover',
  },
  absoluteWrap: {
    position: 'absolute',
    bottom: 30,
    right: 0,
    left: 0,
    gap: 15,
    flexDirection: 'column',
    justifyContent: 'center',
    alignContent: 'center',
    zIndex: 1,
  },
  loader: {
    position: 'absolute',
    bottom: '50%',
    left: 0,
    right: 0,
  },
  flex: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    bottom: 0,
  },
  categoryCard: {
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#ffffff60',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  categoryText: {
    fontSize: 14,
    fontWeight: 400,
    color: '#ffffff60',
  },
  playButton: {
    width: 149,
    height: 44,
    borderRadius: 8,
    backgroundColor: '#fff',
    alignContent: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    bottom: 0,
    alignItems: 'center',
    gap: 5,
    flexDirection: 'row',
  },
  buttonText: {
    fontSize: 17,
    fontWeight: 700,
    color: '#000',
    textAlign: 'center',
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 10,
    gap: 8,
    width: '100%',
  },
  paginationDot: {
    width: 16,
    height: 7,
    borderRadius: 100,
    backgroundColor: '#F30745',
  },
  inactiveDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#ffffff',
  },
});
