export {HomeIcon} from './home';
export {ProfileIcon} from './profile';
export {RewardIcon} from './reward';
export {ShortsIcon} from './shorts';
export {FavoriteIcon} from './favorite';
export {LoveIcon} from './love';
export {ShareIcon} from './share';
export {PlayIcon} from './play';
export {ChevronRightcon} from './chevron-right';
